name: checkin-actions
run-name: ${{ github.actor }} is Checkin

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  release:
    types: [published]
  watch:
    types: [started]

jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -g got@11.8.3

      - run: |
          echo "====== Starting at $(date) ======" >> ./run.log
          node ./checkinL.js >> ./run.log 2>&1
          node ./checkinW.js >> ./run.log 2>&1
          echo "==== Chagee Finished, starting Commune  ====" >> ./run.log
          node ./communeW.>> ./run.log 2>&1
          node ./communeL.js>> ./run.log 2>&1
          echo "========= All Finished ========" >> ./run.log
          tail ./run.log

      - name: Git Configuration
        run: |
          git config --global user.name "DUCk"
          git config --global user.email "arielw@duck.com"
          git add .
          git commit -m "update log" -a

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main

      - run: node ./communeW.js
      - run: node ./communeL.js
