name: checkin-actions
run-name: ${{ github.actor }} is Checkin

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  release:
    types: [published]
  watch:
    types: [started]

jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -g got@11.8.3

      - run: node ./checkinL.js >> ./run.log 2>&1

      - run: tail ./run.log

      - run: node ./checkinW.js >> ./run.log 2>&1

      - run: tail ./run.log

      - env:
          NAME: DUCK
          EMAIL: arielw@duck.com
      - run: |
          git config --global user.name "DUCk"
          git config --global user.email "arielw@duck.com"
          git add .
          git commit -m "update log" -a

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main

      - run: node ./communeW.js
      - run: node ./communeL.js